# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentproxy" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "8976d42132931188d49d30e34cc3c42c745cc4930392bd35579f70ad245b94de"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed71503647c83db05de26563f1f83a8df7d2a538f9fac23cfa5b24bb045eedf8"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ebf5e1662e31ee71f68c8c0600d08530cc3f281a4d392ddccf5ce9322fd3ce1"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8dff7ca189a31359d74d2539dce8318b15f7579df39911b57504709b62e44ae8"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentproxy"
  desc "Hard budget caps for AI coding agents - blocks the next request at the network boundary before it costs more"
  homepage "https://agentproxy.deemwar.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentproxy"

  # No zap stanza required

end
