# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentproxy" do
  version "0.1.8"

  on_macos do
    on_arm do
      sha256 "0f96a2c28a73d6a44ce7b47151caca7ff646451c0f182e6edaeacf445b74eb80"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e90d2c6235933c1cd4f48695db0adaa443626d609a236d7e0c7b7d58c7beeed2"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e5b89e29dacb9574839aad4c66c1ad60eab5ad8ebb71df93e86c1f6eace61bca"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a72af0cb73d3e17e93cba06286dd07b615f57352642e77d94c6d11af6afd84ff"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentproxy"
  desc "Hard budget caps for AI coding agents - blocks the next request at the network boundary before it costs more"
  homepage "https://agentproxy.deemwar.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentproxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
