# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentproxy" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "374f17fae93713a53d3620ec5a9ac6e6d7941d2ff6a36ccd04098ec30b34d380"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed8f92894b8f2394fdfdabfc2e91463c89597460e0090cc762a5f4258020abf1"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "51023bf5c9075a0a0169a5a669209da68ad3f0faefb146be3f000bcb6d9344ff"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c57bae46b2776cd643bf5cab97cb19629ded15fcb19881e06e91d2b65d0d7d85"
      url "https://github.com/deemwar-products/agent-proxy-dist/releases/download/v#{version}/agentproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentproxy"
  desc "Hard budget caps for AI coding agents - blocks the next request at the network boundary before it costs more"
  homepage "https://agentproxy.deemwar.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentproxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
